### ISSUE TITLE
Doesn't show mailbox, throws PHP error: __construct() must be of the type string, array given

### ISSUE THREAD

**Issue by h3artbl33d** [the-djmaze/rainloop-webmail#1]
**RainLoop version, browser, OS:**
`1.14.0-djmaze`

**Expected behavior**
User logs in, messages in inbox get loaded and shown to user.

**Actual behavior:**
User enters credentials, Rainloop drops back to login screen, error gets added to the `error_log`.

**Steps to reproduce the problem:**
I tried to reproduce it myself, it seems to happen _sometimes_ and not bound to an individual user or mailbox - making this incredibly hard to reproduce. I've had this behaviour occur to once of my personal accounts yesterday; when I retried after X time it worked normally.

**Logs or screenshots:**
`Argument 1 passed to MailSo\Imap\Folder::__construct() must be of the type string, array given, called in /var/www/webmail/rainloop/v/1.14.0-djmaze/app/libraries/MailSo/Imap/ResponseCollection.php on line 108`

**Comment by the-djmaze** [comment]
This is indeed a strange bug which i couldn't reproduce.
To get more details, i've modified some code to log the issue.
Try it with this change https://github.com/the-djmaze/rainloop-webmail/commit/0d81b2ce889b626ac69c285dc667664fb39578ed

Would also be nice to know which PHP version and which IMAP server is used.

**Comment by the-djmaze** [comment]
This is indeed a strange bug which i couldn't reproduce.
To get more details, i've modified some code to log the issue.
Try it with this change https://github.com/the-djmaze/rainloop-webmail/commit/0d81b2ce889b626ac69c285dc667664fb39578ed

Would also be nice to know which PHP version and which IMAP server is used.

**Comment by the-djmaze** [comment]
This is indeed a strange bug which i couldn't reproduce.
To get more details, i've modified some code to log the issue.
Try it with this change https://github.com/the-djmaze/rainloop-webmail/commit/0d81b2ce889b626ac69c285dc667664fb39578ed

Would also be nice to know which PHP version and which IMAP server is used.

**Comment by h3artbl33d** [comment]
Thank you for the reply! The server running Rainloop-djmaze is configured with PHP 7.4. Dovecot is being used for IMAP access. Before the switch (to this fork), the webmail server ran Rainloop (upstream) with PHP 7.2, which didn't throw this error. So, it might be either something in the fork or PHP 7.4 that causes this error.

I will throw in the commit tomorrow and get back with the resulting info :)

**Comment by the-djmaze** [comment]
Problem was caused by square brackets because the IMAP response has no quotes around it like:

`sendRaw: TAG2 LSUB "" "*"
* LSUB (\Drafts) "." Drafts
* LSUB (\Sent) "." Sent
* LSUB (\Trash) "." Trash
* LSUB () "." INBOX
* LSUB () "." [gmail]
* LSUB () "." [brackets]
* LSUB () "." "{curly}"
* LSUB () "." "(round)"
* LSUB () "." "[mess](this){up}[cool]"
TAG2 OK Lsub completed (0.001 + 0.000 secs).

ResponseCollection::getFoldersResult: invalid string array (
  0 => 'gmail',
)
ResponseCollection::getFoldersResult: invalid string array (
  0 => 'brackets',
)`
