### ISSUE TITLE
Shared hosting configuration

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/rainloop-webmail#2]
I would love to install your version of Rainloop, but unfortunately I'm on a shared hosting environment and therefore I do not have full access to PHP and Apache configs.

After deploying your version I got the following error:
ERR_CONTENT_DECODING_FAILED 200

Then I thought I could resolve it by adding the Apache config, you mentioned in the Wiki, to a .htaccess file. But then I got a http 500 error.

Do you have some hints to enable your version on a shared hosting environment?

**Comment by the-djmaze** [comment]
ERR_CONTENT_DECODING_FAILED could be caused by double gzip encoding.
In the /rainloop/v/1.14../index.php i've added an ob_start() to gzip encode output.
Turn off the line and check again.

It would be nice to know apache version for the htaccess proper htaccess settings.

**Comment by phsc84** [comment]
I adopted your commit "Resolve issue #2" and it solved the problem! Now it works like a charm. You are great!

**Comment by the-djmaze** [comment]
Thanks!
