### ISSUE TITLE
Drag and drop of emails into folders does not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/rainloop-webmail#8]
**RainLoop version, browser, OS:**
the-djmaze7, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
- select a mail by clicking on it
- drag & drop into a folder => the mail cannot be dropped, instead the prohibition symbol shows up

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
Unfortunately nothing is in the logs and I also cannot screenshot it, because the symbol disappears when the screenshot is taken.
Browser log: 
[log_drag&drop.log](https://github.com/the-djmaze/rainloop-webmail/files/5263495/log_drag.drop.log)

**Comment by the-djmaze** [comment]
Thanks for reporting!
In firefox it works but not in Chrome.
I'm on to something regarding this issue, so i have to rewrite all my dragover events because of Chrome's security.

**Comment by phsc84** [comment]
Works perfectly now! Thanks!

**Comment by the-djmaze** [comment]
Also fixed it for Chrome Mobile.
